"""empty message

Revision ID: 3ce7a3b82d8
Revises: None
Create Date: 2015-05-18 15:05:40.744130

"""

# revision identifiers, used by Alembic.
revision = '3ce7a3b82d8'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    ### end Alembic commands ###
